// prettier-ignore
/* eslint-disable */
// @ts-nocheck
/* auto-generated by NAPI-RS */
const { readFileSync } = require('node:fs')
let nativeBinding = null
const loadErrors = []

const isMusl = () => {
  let musl = false
  if (process.platform === 'linux') {
    musl = isMuslFromFilesystem()
    if (musl === null) musl = isMuslFromReport()
    if (musl === null) musl = isMuslFromChildProcess()
  }
  return musl
}

const isFileMusl = (f) => f.includes('libc.musl-') || f.includes('ld-musl-')
const isMuslFromFilesystem = () => {
  try { return readFileSync('/usr/bin/ldd', 'utf-8').includes('musl') } catch { return null }
}
const isMuslFromReport = () => {
  const report = typeof process.report?.getReport === 'function' ? process.report.getReport() : null
  if (!report) return null
  if (report.header?.glibcVersionRuntime) return false
  if (Array.isArray(report.sharedObjects)) return report.sharedObjects.some(isFileMusl)
  return null
}
const isMuslFromChildProcess = () => {
  try {
    const { execSync } = require('node:child_process')
    const output = execSync('ldd --version', { encoding: 'utf8', stdio: ['pipe', 'pipe', 'pipe'] })
    return output.includes('musl')
  } catch (e) {
    return e?.stderr?.includes('musl') ?? false
  }
}

function requireNative(triple) {
  try { return require(`./fossic.${triple}.node`) } catch (e) { loadErrors.push(e) }
  try { return require(`fossic-${triple}`) } catch (e) { loadErrors.push(e) }
}

switch (process.platform) {
  case 'linux':
    switch (process.arch) {
      case 'x64':
        nativeBinding = isMusl() ? requireNative('linux-x64-musl') : requireNative('linux-x64-gnu')
        break
      case 'arm64':
        nativeBinding = isMusl() ? requireNative('linux-arm64-musl') : requireNative('linux-arm64-gnu')
        break
      default:
        throw new Error(`Unsupported architecture on Linux: ${process.arch}`)
    }
    break
  case 'darwin':
    nativeBinding = process.arch === 'arm64' ? requireNative('darwin-arm64') : requireNative('darwin-x64')
    break
  case 'win32':
    nativeBinding = requireNative('win32-x64-msvc')
    break
  default:
    throw new Error(`Unsupported OS: ${process.platform}`)
}

if (!nativeBinding) {
  if (loadErrors.length > 0) {
    const errorMsg = loadErrors.map(e => e.message || String(e)).join('\n')
    throw new Error(`Failed to load fossic native binding:\n${errorMsg}`)
  }
  throw new Error('Failed to load fossic native binding: unknown error')
}

// ── FossicSubscription JS wrapper ────────────────────────────────────────────
// napi-rs v2 cannot bind well-known symbols (Symbol.asyncIterator /
// Symbol.asyncDispose) via js_name. The native type exposes rawNext() and
// rawDispose(); this wrapper adds the protocol methods on top.
//
// Architecture: a "pump" continuously calls rawNext() one at a time, buffering
// events in JS. next() dequeues from the buffer or registers _pending. Calling
// next() while a previous next() is still pending throws (D5 invariant: only one
// outstanding next() at a time).
class FossicSubscription {
  constructor(native) {
    this._native = native
    this._buffer = []
    this._pending = null
    this._closed = false
    this._pump()
  }

  _pump() {
    if (this._closed) return
    this._native.rawNext((event) => {
      if (this._closed) return
      if (event == null) {
        this._closed = true
        if (this._pending) {
          const resolve = this._pending
          this._pending = null
          resolve({ value: undefined, done: true })
        }
        return
      }
      if (this._pending) {
        const resolve = this._pending
        this._pending = null
        resolve({ value: event, done: false })
      } else {
        this._buffer.push(event)
      }
      this._pump()
    })
  }

  // AsyncIterator protocol
  next() {
    if (this._pending !== null) {
      return Promise.reject(new Error(
        'FossicSubscription.next() called while a previous next() is still pending. ' +
        'Concurrent iteration is not supported — await the previous next() before calling again.'
      ))
    }
    if (this._buffer.length > 0) {
      return Promise.resolve({ value: this._buffer.shift(), done: false })
    }
    if (this._closed) {
      return Promise.resolve({ value: undefined, done: true })
    }
    return new Promise((resolve) => {
      this._pending = resolve
    })
  }

  unsubscribe() {
    if (this._closed) return
    this._closed = true
    this._native.unsubscribe()
    if (this._pending) {
      const resolve = this._pending
      this._pending = null
      resolve({ value: undefined, done: true })
    }
  }

  async [Symbol.asyncDispose]() {
    this.unsubscribe()
  }

  [Symbol.asyncIterator]() {
    return this
  }
}

// Patch Store.subscribe to return the JS wrapper instead of the raw native object.
const _origSubscribe = nativeBinding.Store.prototype.subscribe
nativeBinding.Store.prototype.subscribe = function (...args) {
  return new FossicSubscription(_origSubscribe.apply(this, args))
}

// ── FossicError ──────────────────────────────────────────────────────────────
// Typed error with machine-readable error codes.

const FossicErrorCode = Object.freeze({
  ReducerNotFound: 'ReducerNotFound',
  ReducerError: 'ReducerError',
  StreamNotDeclared: 'StreamNotDeclared',
  GenericFailure: 'GenericFailure',
})

class FossicError extends Error {
  constructor(message, code = FossicErrorCode.GenericFailure) {
    super(message)
    this.name = 'FossicError'
    this.code = code
  }
}

// ── JS-side reducer registry ─────────────────────────────────────────────────
// reducers are stored per-store-instance via a WeakMap so they don't prevent GC.

const _reducerRegistries = new WeakMap()

function _ensureRegistry(store) {
  if (!_reducerRegistries.has(store)) _reducerRegistries.set(store, [])
  return _reducerRegistries.get(store)
}

function _globMatches(pattern, streamId) {
  const pParts = pattern.split('/')
  const sParts = streamId.split('/')
  return _matchParts(pParts, sParts)
}

function _matchParts(p, s) {
  if (p.length === 0 && s.length === 0) return true
  if (p.length === 0) return false
  if (p[0] === '**') {
    for (let n = 0; n <= s.length; n++) {
      if (_matchParts(p.slice(1), s.slice(n))) return true
    }
    return false
  }
  if (s.length === 0) return false
  if (p[0] === '*') return _matchParts(p.slice(1), s.slice(1))
  if (p[0] === s[0]) return _matchParts(p.slice(1), s.slice(1))
  return false
}

function _specificity(pattern) {
  let count = 0
  for (const seg of pattern.split('/')) {
    if (seg === '*' || seg === '**') break
    count++
  }
  return count
}

function _findReducer(registry, streamId) {
  let best = null
  let bestSpec = -1
  for (const { pattern, reducer } of registry) {
    if (_globMatches(pattern, streamId)) {
      const spec = _specificity(pattern)
      if (spec > bestSpec) {
        best = reducer
        bestSpec = spec
      }
    }
  }
  return best
}

// Patch Store prototype with JS-side reducer methods.
const Store = nativeBinding.Store

Store.prototype.registerReducer = function (pattern, reducer) {
  const registry = _ensureRegistry(this)
  registry.push({ pattern, reducer })
}

Store.prototype.readState = async function (streamId, branch = 'main') {
  const registry = _ensureRegistry(this)
  const reducer = _findReducer(registry, streamId)
  if (!reducer) {
    throw new FossicError(
      `no reducer registered for stream ${streamId}`,
      FossicErrorCode.ReducerNotFound,
    )
  }

  const snap = await this.getSnapshotState(
    streamId,
    branch,
    reducer.name,
    reducer.stateSchemaVersion,
  )

  let state, fromVersion
  if (snap != null) {
    state = new Uint8Array(snap.stateBytes.buffer, snap.stateBytes.byteOffset, snap.stateBytes.byteLength)
    fromVersion = snap.version + 1n
  } else {
    state = reducer.initialState()
    fromVersion = 0n
  }

  const events = await this.readRange({ streamId, branch, fromVersion })
  for (const event of events) {
    state = reducer.apply(state, event)
  }

  return state
}

Store.prototype.readStateAtVersion = async function (
  streamId,
  branch = 'main',
  version,
  reducerName,
) {
  const registry = _ensureRegistry(this)
  const reducer = reducerName
    ? registry.find((e) => e.reducer.name === reducerName)?.reducer
    : _findReducer(registry, streamId)
  if (!reducer) {
    throw new FossicError(
      `no reducer registered for stream ${streamId}`,
      FossicErrorCode.ReducerNotFound,
    )
  }

  const snap = await this.getSnapshotState(
    streamId,
    branch,
    reducer.name,
    reducer.stateSchemaVersion,
  )

  let state, fromVersion
  if (snap != null && snap.version < version) {
    state = new Uint8Array(snap.stateBytes.buffer, snap.stateBytes.byteOffset, snap.stateBytes.byteLength)
    fromVersion = snap.version + 1n
  } else {
    state = reducer.initialState()
    fromVersion = 0n
  }

  const events = await this.readRange({ streamId, branch, fromVersion, toVersion: version })
  for (const event of events) {
    state = reducer.apply(state, event)
  }

  return state
}

// ── TruncationCursor ──────────────────────────────────────────────────────────
// napi-rs exports the class under its Rust struct name (TruncationCursorJs).
// Re-export as TruncationCursor for user-facing ergonomics.

const TruncationCursor = nativeBinding.TruncationCursorJs

// ── Async iterator wrappers ───────────────────────────────────────────────────
// napi-rs cannot bind Symbol.asyncIterator via js_name.
// Native types expose rawNext(); these wrappers add the AsyncIterator protocol.

class FossicRangeIter {
  constructor(native) {
    this._native = native
    this._done = false
  }

  async next() {
    if (this._done) return { value: undefined, done: true }
    const value = await this._native.rawNext()
    if (value == null) {
      this._done = true
      return { value: undefined, done: true }
    }
    return { value, done: false }
  }

  [Symbol.asyncIterator]() { return this }

  async [Symbol.asyncDispose]() {}
}

class FossicCorrelationIter {
  constructor(native) {
    this._native = native
    this._done = false
  }

  async next() {
    if (this._done) return { value: undefined, done: true }
    const value = await this._native.rawNext()
    if (value == null) {
      this._done = true
      return { value: undefined, done: true }
    }
    return { value, done: false }
  }

  [Symbol.asyncIterator]() { return this }

  async [Symbol.asyncDispose]() {}
}

class FossicCausationIter {
  constructor(native) {
    this._native = native
    this._done = false
  }

  async next() {
    if (this._done) return { value: undefined, done: true }
    const value = await this._native.rawNext()
    if (value == null) {
      this._done = true
      return { value: undefined, done: true }
    }
    return { value, done: false }
  }

  [Symbol.asyncIterator]() { return this }

  async [Symbol.asyncDispose]() {}
}

// Patch Store iter methods to return JS iterator wrappers.
const _origReadRangeIter = nativeBinding.Store.prototype.readRangeIter
nativeBinding.Store.prototype.readRangeIter = function (...args) {
  return new FossicRangeIter(_origReadRangeIter.apply(this, args))
}

const _origReadByCorrelationIter = nativeBinding.Store.prototype.readByCorrelationIter
nativeBinding.Store.prototype.readByCorrelationIter = function (...args) {
  return new FossicCorrelationIter(_origReadByCorrelationIter.apply(this, args))
}

const _origWalkCausationIter = nativeBinding.Store.prototype.walkCausationIter
nativeBinding.Store.prototype.walkCausationIter = function (...args) {
  return new FossicCausationIter(_origWalkCausationIter.apply(this, args))
}

// ── Bounded read cursor conversion ────────────────────────────────────────────
// Native bounded methods accept/return raw Buffer for cursors.
// These patches convert TruncationCursor↔Buffer transparently.

function _cursorToBuffer(cursor) {
  if (cursor == null) return null
  if (cursor instanceof TruncationCursor) return cursor.toBytes()
  if (Buffer.isBuffer(cursor)) return cursor
  return null
}

function _wrapOutcomeCursor(outcome) {
  if (outcome != null && outcome.nextCursor != null) {
    outcome.nextCursor = TruncationCursor.fromBytes(outcome.nextCursor)
  }
  return outcome
}

const _origReadRangeBounded = nativeBinding.Store.prototype.readRangeBounded
nativeBinding.Store.prototype.readRangeBounded = async function (query, maxResults, maxBytes, cursor) {
  const outcome = await _origReadRangeBounded.call(this, query, maxResults, maxBytes, _cursorToBuffer(cursor))
  return _wrapOutcomeCursor(outcome)
}

const _origReadByCorrelationBounded = nativeBinding.Store.prototype.readByCorrelationBounded
nativeBinding.Store.prototype.readByCorrelationBounded = async function (correlationId, maxResults, maxBytes, cursor) {
  const outcome = await _origReadByCorrelationBounded.call(this, correlationId, maxResults, maxBytes, _cursorToBuffer(cursor))
  return _wrapOutcomeCursor(outcome)
}

const _origWalkCausationBounded = nativeBinding.Store.prototype.walkCausationBounded
nativeBinding.Store.prototype.walkCausationBounded = async function (start, direction, maxDepth, sampling, maxResults, maxBytes, cursor) {
  const outcome = await _origWalkCausationBounded.call(this, start, direction, maxDepth, sampling, maxResults, maxBytes, _cursorToBuffer(cursor))
  return _wrapOutcomeCursor(outcome)
}

// ── SamplingMode namespace ────────────────────────────────────────────────────

const SamplingMode = Object.freeze({
  exhaustive: () => ({ kind: 'exhaustive' }),
  breadthFirst: (maxPerLevel) => ({ kind: 'breadthFirst', maxPerLevel }),
  adaptive: (targetCount) => ({ kind: 'adaptive', targetCount }),
})

module.exports = nativeBinding
module.exports.EventId = nativeBinding.EventId
module.exports.FossicSubscription = FossicSubscription
module.exports.Store = nativeBinding.Store
module.exports.fossicVersion = nativeBinding.fossicVersion
module.exports.FossicError = FossicError
module.exports.FossicErrorCode = FossicErrorCode
module.exports.TruncationCursor = TruncationCursor
module.exports.FossicRangeIter = FossicRangeIter
module.exports.FossicCorrelationIter = FossicCorrelationIter
module.exports.FossicCausationIter = FossicCausationIter
module.exports.SamplingMode = SamplingMode
